[package]
name = "compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
genawaiter = "^0.99"
libc = "^0.2"
pest = "^2.7"
pest_derive = "^2.7"
rustc-hash = "^2.1"

[features]
default = ["hardware_vfp"]
debug_output = []
hardware_vfp = []
