name: Mirroring

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: ${{ secrets.REPO_URL }}
          GIT_USERNAME: ${{ secrets.USERNAME }}
          GIT_PASSWORD: ${{ secrets.PASSWORD }}
